apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  metadata:
    name: Playwright Hello World
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
docker:
  image:
    name: saucelabs/stt-playwright-folio-node
    tag: latest
playwright:
  projectPath: ./tests/
  param:
    browserName: "webkit"
suites:
  - name: "default"
    param:
      browserName: "webkit"
      slowMo: 10000
    testMatch: "**/*.spec.js"

